language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake

before_install:
  pip install --user cpp-coveralls


script:
  - cmake -DCOVERAGE=1 .
  - cmake --build .
  - ./transaction_test
  - ./account_test

after_success:
  after_success:
    - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
