language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake

before_install:
  pip install --user cpp-coveralls


script:
    - mkdir build
    - cmake -H. -B build
    - cmake -D COVERAGE=1 build
    - cmake --build build
    - ./build/test_account
    - ./build/test_transaction

after_success:
  after_success:
    - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
